name: release-please
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    container: ghcr.io/pikdum/ebb/builder:latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.PAT }}
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - run: git config --global safe.directory '*'
        if: ${{ steps.release.outputs.release_created }}
      - run: ./scripts/publish.sh
        if: ${{ steps.release.outputs.release_created }}
        env:
          GH_TOKEN: ${{ github.token }}
