name: test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run test
        env:
          SETTING_GELBOORU_API_CREDENTIALS: ${{ secrets.SETTING_GELBOORU_API_CREDENTIALS }}
      - run: npm run build
      - run: npm run package:linux
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - uses: biomejs/setup-biome@v2
      - run: biome check . --write
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: biome check . --write"
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run check-types
